les commandes utilisé au workshop !!!!
1. La Commande pwd
Cette commande permet d’afficher l’emplacement ou on se situe actuellement dans la hiérarchie FHS.

 Ex:  [root@centos ~]# pwd/root

2. La Commande cd
Cette commande permet de changer de répertoire courant et de se situer sur un autre

Ex : [omar@katim ~]# cd /home/
     [omar@katim home]# pwd/home
     
3. La Commande lscommande1
Permet de lister les fichiers disponibles dans un répertoire, si appelé sans arguments, ls liste les fichiers du répertoire courant.

Ex   [omar@katim home]# ls user1 user2
=> Ainsi, dans le répertoire home, deux fichiers existent et sont : user1 et user2

4. La Commande mkdir
Cette commande permet de créer un répertoire.

[omar@katim home]# cd /tmp
[omar@katim tmp]# pwd
/tmp
[omar@katim tmp]# mkdir repertoiredetest
[omar@katim tmp]# ls
repertoiredetest
fichiertemp
=> Dans cet exemple, on s’est déplacé sous le répertoire tmp disponible sous la racine /,  affiché notre emplacement gràce à la commande pwd, puis créé un répertoire (dossier) nomé repertoiredetest et le visualisé avec la commande ls.

5. La Commande rmdir
Cette commande permet de supprimer un répertoire.

[omar@katim tmp]# rmdir repertoiredetest
[omar@katim tmp]# ls
fichiertemp
=> Avec cette commande, on vient de supprimer le répertoire qu’on vient de créer et la commande ls nous l’a confirmé.

6. La Commande touch
Cette commande permet de changer la date du dernier accès ou modification d’un fichier, mais permet également de créer un fichier vide.

[omar@katim tmp]# touch fichier
[omar@katim tmp]# ls
fichier
fichiertemp
=> De même, mais cette fois, on a créé un fichier nommé fichier.

7. La Commande cp
Cette commande permet de copier un fichier ou un répertoire.

[omar@katim tmp]# cp fichier fichier2
[omar@katim tmp]# ls
fichier 
fichier2
fichiertemp
=> Avec la commande cp, on a copié le fichier fichier en le nommant fichier2.

8. La Commande rm
Cette commande permet de supprimer un fichier ou un répertoire. Cette commande est à utiliser avec précaution car avec l’option -f ou -rf, cette commande peut endommager voir supprimer tout votre système de fichiers de manière irréversible.

[omar@katim tmp]# rm -f fichier fichier2
[omar@katim tmp]# ls
fichiertemp
=> La commande rm nous a permit dans cet exemple de supprimer les deux fichiers précédemment créés.

9 La Commande mv
Cette commande sert à renommer ou déplacer un fichier ou un répertoire.

Dans l’exemple suivant, on va créer un fichier nommé “fichier3”, et à l’aide de la commande mv, on va le renommer en “fichier4” et le déplacer dans le répertoire “/home” en une seule fois.

[omar@katim tmp]# touch fichier3
[omar@katim tmp]# mv fichier3 /home/fichier4
[omar@katim tmp]# ls /home/
fichier4 user1 user2
11. La Commande cat
Cette commande permet d’afficher le contenu d’un fichier.

[omar@katim tmp]# cat /home/fichier4
[omar@katim tmp]#
le fichier “fichier4” est vide, donc la commande “cat” ne renverra aucun résultat, dans un autre cas on pourrait avoir :

[omar@katim tmp]# cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 8.8.8.8
Souvenez-vous que /etc/ contient principalement des fichiers de configuration, ici, le fichier resolv.conf est le fichier qui détient les informations DNS de notre système (8.8.8.8 est l’adresse IP du serveur DNS de google).

12. La Commande echo
Cette commande permet d’afficher une ligne.

[omar@katim tmp]# echo "tutoriel Linux de sitedetout"
tutoriel Linux de sitedetout
=> echo permet aussi d’écrire du contenu dans un fichier moyennant le signe “>” pour écraser le contenu du fichier ou “>>” pour suffixer le contenu du fichier.


13. La Commande man
Cette commande permet d’afficher le manuel d’aide de n’importe quelle autre commande disponible, ex : man ls

man ls

Tapez la lettre q pour fermer la page du manuel.

14. La Commande ln
Cette commande est utilisée pour créer un lien matériel ou symbolique (raccourci) vers un fichier ou un répertoire.


14. La Commande which
Cette commande permet de visualiser l’emplacement d’une commande en effectuant une recherche dans  différents répertoires.

[root@centos tmp]# which pwd

/bin/pwd

[root@centos tmp]# which mkdir

/bin/mkdir
